spring.application.name=HomiFy-Backend

# =========================================================
# DATABASE CONFIGURATION (PostgreSQL via Docker)
# =========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/homify_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA / HIBERNATE CONFIGURATION
# =========================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================================================
# SERVER CONFIGURATION
# =========================================================
server.port=8080

# =========================================================
# LOGGING
# =========================================================
logging.level.org.springframework.web=INFO
logging.level.com.homifybackend=DEBUG

# =========================================================
# DISABLE MONGODB AUTO-CONFIGURATION
# =========================================================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
