spring.application.name=HomiFy-Backend
server.port=${SERVER_PORT:8080}
server.address=0.0.0.0

# Disable MongoDB auto-configuration
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

# PostgreSQL Database Configuration (Supabase)
#spring.datasource.url=jdbc:postgresql://localhost:5432/homify_dev
#spring.datasource.username=postgres
#spring.datasource.password=bigK2909@
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ddggagayapoapetenquj
spring.datasource.password=Homify23133
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#HikariCP
spring.datasource.hikari.pool-name=HikariPool

# Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0

# Zestimate ML Configuration
zestimate.python.path=python
zestimate.script.path=ml/predict.py
zestimate.timeout.seconds=30



logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG

logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.boot.context.config=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

mail.from=${MAIL_FROM}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}
app.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
app.jwt.remember-me-expiration=${JWT_REMEMBER_ME_EXPIRATION:2592000000}

app.google.client-id=${GOOGLE_CLIENT_ID}
app.google.client-secret=${GOOGLE_CLIENT_SECRET}
app.google.redirect-uri=${GOOGLE_REDIRECT_URI}

app.otp.expiration-minutes=${OTP_EXPIRATION}
app.otp.length=${OTP_LENGTH}

app.frontend.url=${FRONTEND_URL}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}