spring.application.name=HomiFy-Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/homify_dev
spring.datasource.username=postgres
spring.datasource.password=bigK2909@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
